version: '3.8'

services:
  backend_db:
    container_name: backend_db
    image: mysql:8.0.37
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: products
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ./data/db:/var/lib/mysql

  springboot_products:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_products
    restart: unless-stopped
    ports:
      - 8088:8080
    expose:
      - 8080
    depends_on:
      - backend_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://backend_db:3306/products
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
