spring:
  application:
    name: products-microservice

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/products?useSSL=false}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

server:
  port: ${PORT:8088}

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: products-microservice